development:
  adapter: postgresql
  encoding: unicode
  database: message_development
  pool: 5
  username: skydb
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: message_test
  pool: 5
  username: skydb
  password: postgres


production:
  adapter: postgresql
  encoding: unicode
  database: message_production
  pool: 5
  username: skydb
  password: postgres
